env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1"

window:
  dimensions:
    columns: 80
    lines: 40

  padding:
    x: 0
    y: 0

  dynamic_padding: false

  decorations: full

  startup_mode: Windowed

  dynamic_title: true

scrolling:
  history: 2500
  multiplier: 3

font:
  normal:
    family: Noto Sans Mono
    style: Regular

  bold:
    family: Noto Sans Mono
    style: Bold

  italic:
    family: Noto Sans Mono
    style: Italic

  bold_italic:
    family: Noto Sans Mono
    style: Bold Italic

  size: 9.5

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

# Oxide colors
colors:
  primary:
    background: '#393939'
    foreground: '#F9F9F9'
    bright_foreground: '#FFF5EB'

  cursor:
    text: '#212121'
    cursor: '#c0c5ce'
    
  normal:
    black:   '#212121'
    red:     '#D83A56'
    green:   '#289672'
    yellow:  '#FFCB91'
    blue:    '#07689F'
    magenta: '#BA135D'
    cyan:    '#A6DCEF'
    white:   '#c0c5ce'

  bright:
    black:   '#5c5c5c'
    red:     '#FF616D'
    green:   '#29BB89'
    yellow:  '#FFEFA1'
    blue:    '#40A8C4'
    magenta: '#E93B81'
    cyan:    '#DDF3F5'
    white:   '#EDF6E5'

  indexed_colors: []

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'

background_opacity: 0.98

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style: Beam
  vi_mode_style: None
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: false

working_directory: None

alt_send_esc: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  hide_when_typing: false

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

key_bindings:
  - { key: Paste,                                         action: Paste            }
  - { key: Copy,                                          action: Copy             }
  - { key: L,              mods: Control,                 action: ClearLogNotice   }
  - { key: L,              mods: Control, mode: ~Vi,      chars: "\x0c"            }
  - { key: PageUp,         mods: Shift,   mode: ~Alt,     action: ScrollPageUp,    }
  - { key: PageDown,       mods: Shift,   mode: ~Alt,     action: ScrollPageDown   }
  - { key: Home,           mods: Shift,   mode: ~Alt,     action: ScrollToTop,     }
  - { key: End,            mods: Shift,   mode: ~Alt,     action: ScrollToBottom   }
  - { key: V,              mods: Control,           action: Paste            }
  - { key: C,              mods: Control,           action: Copy             }
  - { key: F,              mods: Control|Shift,           action: SearchForward    }
  - { key: B,              mods: Control|Shift,           action: SearchBackward   }
  - { key: C,              mods: Control|Shift, mode: Vi, action: ClearSelection   }
  - { key: Insert,         mods: Shift,                   action: PasteSelection   }
  - { key: Key0,           mods: Control,                 action: ResetFontSize    }
  - { key: Equals,         mods: Control,                 action: IncreaseFontSize }
  - { key: Plus,           mods: Control,                 action: IncreaseFontSize }
  - { key: NumpadAdd,      mods: Control,                 action: IncreaseFontSize }
  - { key: Minus,          mods: Control,                 action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Control,                 action: DecreaseFontSize }

debug:
  render_timer: false
  persistent_logging: false
  log_level: Warn
  print_events: false
